[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "hosts"
    name = "Hosts"
    url = "/hosts"
    weight = 3

[[main]]
    identifier = "episodes"
    name = "Episodes"
    url = "/episodes"
    weight = 2

# Social Media Configuration
# 
# [[social]]
#     identifier = "twitter"
#     name = "Twitter"
#     url = "#"
#     weight = 1
# 
# [[social]]
#     identifier = "instagram"
#     name = "Instagram"
#     url = "#"
#     weight = 2
# 
# [[social]]
#     identifier = "github"
#     name = "GitHub"
#     url = "#"
#     weight = 3